packages:
  # - repos/**/*
  # https://github.com/iTwin/itwinjs-core
  - "repos/itwinjs-core/core/*"
  - "repos/itwinjs-core/presentation/*"
  - "repos/itwinjs-core/tools/*"
  - "repos/itwinjs-core/ui/*"
  # https://github.com/iTwin/viewer
  - "repos/viewer/common/scripts"
  - "repos/viewer/packages/apps/web-viewer-test"
  - "repos/viewer/packages/apps/desktop-viewer-test"
  - "repos/viewer/packages/modules/*"
  - "!repos/viewer/packages/modules/cra-*"
